config/routes.rb
RecipeCompiler::Application.routes.draw do
  resources :users

  resources :votes, :only => [:create] do
    collection do
      post 'subtract'
    end
  end

  resources :topics

  root :to => 'topics#index'
  
  post "login" => 'users#login'
  post "logout" => 'users#logout'
  

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Topic < ActiveRecord::Base
  attr_accessible :title, :description, :user, :username
  
  belongs_to :user
  has_many :votes

  validates_presence_of :title
  validates_presence_of :description

  def username
    user.name rescue ""
  end

  def votes_by_user_id(user_id)
    votes.where(:user_id => user_id)
  end
  
  def logged_in_as_author (user_id)
    current_user = User.find(user_id) rescue nil
    user == nil or user == current_user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :topics, :votes
  
  has_many :topics
  has_many :votes
  
  validates_presence_of :name
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :integer
#  user_id    :integer
#

class Vote < ActiveRecord::Base
  attr_accessible :topic_id
  
  belongs_to :topic
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :logged_in_as_author, :only => [:edit, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @ip = request.remote_ip

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    if session[:user_id]
      @topic.user = User.find(session[:user_id])
    end

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  def logged_in_as_author
    topic = Topic.find(params[:id])
    unless topic.logged_in_as_author(session[:user_id])
      redirect_to(topics_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    user = User.find_or_create_by_name(params[:name])
    session[:user_id] = user.id
    redirect_to(topics_path)
  end
  def logout
    user = User.find_or_create_by_name(params[:name])
    session[:user_id] = nil
    redirect_to(topics_path)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    topic = Topic.find(params[:topic_id])
    user = User.find(session[:user_id])
    # first, check if there are any existing votes from this user!
    if topic.votes_by_user_id(session[:user_id]).empty?
      vote = topic.votes.build
      vote.user = user
      vote.save!
    end
    redirect_to(topics_path)
  end

  def subtract
    topic = Topic.find(params[:topic_id])
    vote = topic.votes_by_user_id(session[:user_id]).first rescue nil
    if vote
      vote.destroy
    end
    redirect_to(topics_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_header.html.erb
<% if session[:user_id] %>
  <%= form_tag '/logout' do %>
    <p>
      Currently logged in as <b><%= User.find(session[:user_id]).name %></b>
      <%= submit_tag 'Log out' %>
    </p>
  <% end %>
<% else %>
  <%= form_tag '/login' do %>
    <p>Log in as: <%= text_field :name, :name %> <%= submit_tag 'Log in' %></p>
  <% end %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeCompiler</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Awesome Recipes</h1>

<table>
  <tr style="padding:1px; border-bottom:1px solid black">
    <th style="padding:1px"><em>Recipe</em></th>
    <th style="padding:1px; border-left:1px solid black;"><em>Creator</em></th>
    <th style="padding:1px; border-left:1px solid black;"><em>Popularity</em></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td style="padding:1px;"><%= link_to topic.title, topic %></td>
    <td style="padding:1px; border-left:1px solid black;"><%= topic.username %></td>
    <td style="padding:1px; border-left:1px solid black;"><%= pluralize(topic.votes.length,"vote") %></td>
    <% if session[:user_id] %>
      <% if topic.votes_by_user_id(session[:user_id]).empty? %>
        <td><%= button_to '+1', votes_path(topic_id: topic.id), method: :post %></td>
      <% else %>
        <td><%= button_to '-1', subtract_votes_path(topic_id: topic.id), method: :post %></td>
      <% end %>
    <% end %>
    <% delete_msg = topic.logged_in_as_author(session[:user_id]) ? 'Once you delete this, it will be gone forever.  Can you live with that?' : 'Try to delete this!' %>
    <td><%= link_to 'Delete', topic, confirm: delete_msg, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <strong><span style="color:blue"><%= @topic.title %></span></strong>
</p>

<p>
  <b>Description:</b>
  <%= simple_format @topic.description %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>